version: "3"
services:
  dex:
    container_name: dex
    image: ghcr.io/dexidp/dex:v2.27.0
    networks:
      - web
    volumes:
      - ./dex-config.yml:/etc/dex/config.yml:ro
      - /var/dex:/var/dex/
    ports:
      - 5556:5556 # dex
      - 5557:5557 # /metrics
    command: ["serve", "/etc/dex/config.yml"]

networks:
  web:
    external: true